language: php
php:
  - '5.6'
  - '7.0'
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
before_script:
  - phpenv config-rm xdebug.ini
  - composer install
  - cp .env.example .env
  - sed -i 's/\/path\/to\/data/tests\/assets\/dummy.txt/' .env
  - sed -i 's/username/travis/' .env
  - sed -i 's/password//' .env
  - sed -i 's/dbname/test/' .env
script: phpunit --bootstrap bootstrap.php tests/
